---
apiVersion: v1
kind: Template
metadata:
  name: myapp-dc-template
  annotations:
    description: DeploymentConfig template for ${APP_NAME} app on OCP
    tags: example,template
  labels:
    app: ${APP_NAME}
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      replicas: ${{REPLICA_COUNT}}
      selector:
        app: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              image: ${APP_IMAGE}
              imagePullPolicy: Always
              ports:
                - containerPort: ${{APP_HTTP_PORT}}
                  protocol: TCP
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-cfg-appenv
                - secretRef:
                    name: ${APP_NAME}-sec-appenv
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
parameters:
  - name: APP_NAME
    description: Name of the application.
    required: true
  - name: APP_IMAGE
    description: "App image full url: [registry-url]/[namespace]/[image]:[tag]"
    required: true
  - name: APP_HTTP_PORT
    description: "Application HTTP port."
    required: true
  - name: REPLICA_COUNT
    description: "No of replicas/instances of the app."
    value: '2' # default to 2 replicas
    required: true
