---
# ImageStream template for App Base Image
apiVersion: v1
kind: Template
metadata:
  name: myapp-is-baseimg-template
  annotations:
    description: ImageStream template for ${APP_NAME} app base container image on OCP
    tags: example,template
  labels:
    app: ${APP_NAME}
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${BASE_IS_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      tags:
        name: ${BASE_IST_NAME}
        from:
          kind: DockerImage
          name: ${BASE_IMAGE}
        # referencePolicy:
        #   type: Source
      lookupPolicy:
        local: false
parameters:
  - name: APP_NAME
    description: Name of the application.
    required: true
  - name: BASE_IMAGE
    description: "Base container image for the app. Image full url as [registry-url]/[namespace]/[image]:[tag]"
    required: true
  - name: BASE_IS_NAME
    description: Base imagestrem name.
    required: true
  - name: BASE_IST_NAME
    description: Tag for the app base image.
    value: 'latest'
    required: true
