---
# ImageStream template for App Image
apiVersion: v1
kind: Template
metadata:
  name: myapp-is-appimg-template
  annotations:
    description: ImageStream template for ${APP_NAME} app container image on OCP
    tags: example,template
  labels:
    app: ${APP_NAME}
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${APP_IS_NAME}
      labels:
        app: ${APP_NAME}
parameters:
  - name: APP_NAME
    description: Name of the application.
    required: true
  - name: APP_IS_NAME
    description: Name of the app imagestream.
    required: true
    