---
apiVersion: v1
kind: Template
metadata:
  name: myapp-route-template
  annotations:
    description: Route template for ${APP_NAME} app on OCP
    tags: example,template
  labels:
    app: ${APP_NAME}
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      #host: <if you need custom hostname, specify here>
      port:
        targetPort: "http-unsec"
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      tls:
        termination: edge
      wildcardPolicy: None
parameters:
  - name: APP_NAME
    description: Name of the application.
    required: true
