---
apiVersion: v1
kind: Template
metadata:
  name: myapp-svc-template
  annotations:
    description: Service template for ${APP_NAME} app on OCP
    tags: example,template
  labels:
    app: ${APP_NAME}
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      type: ClusterIP
      sessionAffinity: None
      ports:
        - name: "http-unsec"
          port: 9080
          protocol: TCP
          targetPort: ${{APP_HTTP_PORT}} # container port
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
parameters:
  - name: APP_NAME
    description: Name of the application.
    required: true
  - name: APP_HTTP_PORT
    description: "Application HTTP port."

    required: true
